name: Main

on:
  push:
    branches:
    - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.BMASTERS_ACTOR }}
        password: ${{ secrets.BMASTERS_TOKEN }}

    - name: StormForger Docker meta
      id: stormforger_docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ghcr.io/${{ github.repository }}
        tag-sha: true
        tag-edge: true
        sep-tags: -stormforger,
    - name: StormForger build and push
      id: stormforger_docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./stormforger
        file: ./stormforger/Dockerfile
        push: true
        tags: ${{ steps.stormforger_docker_meta.outputs.tags }}-stormforger
        #labels: ${{ steps.stormforger_docker_meta.outputs.labels }}
        labels: 'org.opencontainers.image.source=https://github.com/${{ github.repository }}'
    - name: StormForger image digest
      run: echo ${{ steps.stormforger_docker_build.outputs.digest }}
