name: Main

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.BMASTERS_ACTOR }}
        password: ${{ secrets.BMASTERS_TOKEN }}

    - name: Set up Docker Buildx for StormForger
      uses: docker/setup-buildx-action@v1
      id: stormforger_builder
    - name: StormForger Docker meta
      id: stormforger_docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ghcr.io/${{ github.repository }}
        tag-sha: true
        tag-edge: true
        sep-tags: -stormforger,
    - name: StormForger build and push
      id: stormforger_docker_build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.stormforger_builder.outputs.name }}
        context: ./stormforger
        file: ./stormforger/Dockerfile
        push: true
        tags: ${{ steps.stormforger_docker_meta.outputs.tags }}-stormforger
        labels: ${{ steps.stormforger_docker_meta.outputs.labels }}
    - name: StormForger image digest
      run: echo ${{ steps.stormforger_docker_build.outputs.digest }}

    - name: Set up Docker Buildx for Locust
      uses: docker/setup-buildx-action@v1
      id: locust_builder
    - name: Locust Docker meta
      id: locust_docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ghcr.io/${{ github.repository }}
        tag-sha: true
        tag-edge: true
        sep-tags: -locust,
    - name: Locust build and push
      id: locust_docker_build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.locust_builder.outputs.name }}
        context: ./locust
        file: ./locust/Dockerfile
        push: true
        tags: ${{ steps.locust_docker_meta.outputs.tags }}-locust
        labels: ${{ steps.locust_docker_meta.outputs.labels }}
    - name: Locust image digest
      run: echo ${{ steps.locust_docker_build.outputs.digest }}
